import type { Metadata } from "next";
import "./globals.css";

import { fontList } from "@/fonts/font-webhook";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

const mapedFonts = fontList.map((font) => font.variable);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mapedFonts.join(
          " "
        )} antialiased font-yekan-regular overflow-x-hidden`}
      >
        <Providers>{children}</Providers>
        <Toaster
          theme="light"
          richColors
          className="font-yekan-regular! text-right!"
        />
      </body>
    </html>
  );
}
