import type { Metadata } from "next";
import "./globals.css";

import { vazirRegular, vazirSemiBold } from "./fonts/font-webhook";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vazirRegular.variable} ${vazirSemiBold.variable} antialiased font-vazir-regular`}
      >
        {children}
      </body>
    </html>
  );
}
