import type { Metadata } from "next";
import "./globals.css";

import {
  yekanBakhRegular,
  yekanBakhSemiBold,
  yekanBakhBlack,
} from "./fonts/font-webhook";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${yekanBakhRegular.variable} ${yekanBakhSemiBold.variable} ${yekanBakhBlack.variable} antialiased font-yekan-regular`}
      >
        {children}
      </body>
    </html>
  );
}
